services:
  db:
    image: postgres:16-alpine
    container_name: vaniguard-postgres
    environment:
      POSTGRES_USER: vaniguard
      POSTGRES_PASSWORD: vanipass123
      POSTGRES_DB: vaniguard_db
    ports:
      - "5433:5432"
    volumes:
      - vaniguard_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaniguard -d vaniguard_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  vaniguard_pg_data:
